on:
  push:
    branches:
      - 'main'
#      - 'build-*'

jobs:
  sync-vagrant-vmware-desktop:
    if: github.repository == 'hashicorp/vagrant-vmware-desktop-builder'
    runs-on: ubuntu-18.04
    steps:
      - name: Code Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Set Ruby
        uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
        with:
          ruby-version: '2.6'
      - name: Sync vagrant-vmware-desktop Repository
        run: ./.ci/sync.sh
        working-directory: ${{github.workspace}}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ASSUME_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
          HASHIBOT_TOKEN: ${{ secrets.HASHIBOT_TOKEN }}
          HASHIBOT_USERNAME: ${{ secrets.HASHIBOT_USERNAME }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          VAGRANT_CI_LOADER_BUCKET: ${{ secrets.VAGRANT_CI_LOADER_BUCKET }}

  sync-vagrant-vmware-desktop-builder:
    if: github.repository == 'hashicorp/vagrant-vmware-desktop'
    runs-on: ubuntu-18.04
    steps:
      - name: Code Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Set Ruby
        uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
        with:
          ruby-version: '2.6'
      - name: Sync vagrant-vmware-desktop-builder Repository
        run: ./.ci/sync.sh
        working-directory: ${{github.workspace}}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ASSUME_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
          HASHIBOT_TOKEN: ${{ secrets.HASHIBOT_TOKEN }}
          HASHIBOT_USERNAME: ${{ secrets.HASHIBOT_USERNAME }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          VAGRANT_CI_LOADER_BUCKET: ${{ secrets.VAGRANT_CI_LOADER_BUCKET }}
