on:
  push:
    tags:
      - 'desktop-v*'

jobs:
  release:
    if: github.repository == 'hashicorp/vagrant-vmware-desktop-builder'
    name: Vagrant VMware Desktop Plugin Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Code Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # set this so we can push our branch later
      - name: Setup Ruby
        uses: actions/setup-ruby@v1 # TSCCR: no versions of "actions/setup-ruby" are trusted
        with:
          ruby-version: '3.1'
      - name: Build Vagrant VMware Desktop Plugin
        id: build
        run: ./.ci/build-plugin
      - name: Create Local Release
        run: . ./.ci/load-ci.sh && release "${GITHUB_REF##*tags/}" "${GEM_PATH}"
        env:
          GEM_PATH: ${{ steps.build.outputs.gem-path }}
      - name: Push Branch to Publish
        run: ./.ci/push-publish-branch
        env:
          PUBLISH_BRANCH: ${{ secrets.HASHIGEMS_PUBLISH_BRANCH }}
