on:
  schedule:
    - cron: '12 5 * * *'
  workflow_dispatch:

jobs:
  prune-drafts:
    if: github.repository == 'hashicorp/vagrant-vmware-desktop-builders'
    name: Prune stale draft releases
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Code Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - name: Prune any drafts older than 20 days
        run: . ./.ci/load-ci.sh && github_draft_release_prune "20"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
