on:
  push:
    branches:
      - 'build-utility-*'
  schedule:
    - cron: '15 1 * * *'

jobs:
  build-utilities:
    if: github.repository == 'hashicorp/vagrant-vmware-desktop'
    name: Development Utility Builds
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Code Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - name: Setup Go
        uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 # v4.0.0
        with:
          go-version-file: go.mod
      - name: Get version
        id: info
        run: ./.ci/utility-information
      - name: Build utilities
        run: make all
      - name: Publish utilities
        run: . ./.ci/load-ci.sh && prerelease "${UTILITY_VERSION}" ./bin
        env:
          UTILITY_VERSION: ${{ steps.info.outputs.utility-version }}
